### ISSUE TITLE
mumble will not connect from wan side if no redirection to lan ip is set in the firewall

### ISSUE THREAD

**Issue by elgatov** [umurmur/umurmur#131]
Hello,

I have umurmur installed in OpenWRT and finally have fixed a problem I had in which the server was not appearing for the wan side.

This are the rules I had to set in the firewall config for it to work properly:
```
config rule
    option target 'ACCEPT'
    option src 'wan'
    option proto 'tcp udp'
    option dest_port '64738'
    option name 'µMurmur'

config redirect
    option target 'DNAT'
    option src 'wan'
    option dest 'lan'
    option proto 'tcp udp'
    option src_dport '64738'
    option dest_ip '192.168.1.1'
    option dest_port '64738'
    option name 'µMurmur'


```

If I disable the redirection I still can connect to the server from lan side, but not from wan.

This is my umurmur.conf:
```
max_bandwidth = 130000;

# bindport = 64738;
# bindaddr = "192.168.1.1";

# Log to file option. Default is logging to syslog.
# umurmurd will close and reopen the logfile if SIGHUP is received.
logfile = "/var/log/umurmurd.log";

#imagemessagelength = 131072
#allowhtml = true

```

Version is uMurmur version 0.2.16a ('Agrajag') protocol version 1.2.4

**Comment by unterwulf** [comment]
If bindaddr is not specified either in the config file or as a command-line option umurmur will bind to address 0.0.0.0 which is all local interfaces. So I'd suspect that the problem is somewhere in the firewall configuration.

You can use netstat -l to ensure that umumur is actually bound to *:64738. It'd be surprising if it's not.

To investigate if the firewall is configured properly I'd stop umurmur and run netcat instead to listen on port 64738 and try to connect from the wan side. If netcat wouldn't print anything then umurmur has nothing to do with your issue.
