### ISSUE TITLE
umurmur don't start on openwrt

### ISSUE THREAD

**Issue by artemklevtsov** [umurmur/umurmur#65]
``` bash
root@router:~# /etc/init.d/umurmur start
/usr/bin/umurmurd: unrecognized option: r
Unrecognized option
uMurmur version 0.2.16 ('Agrajag'). Mumble protocol 1.2.4
Usage: umurmurd [-d] [-r] [-h] [-p <pidfile>] [-t] [-c <conf file>] [-a <addr>] [-b <por
       -d             - Do not daemonize - run in foreground.
       -p <pidfile>   - Write PID to this file
       -c <conf file> - Specify configuration file (default /etc/umurmur.conf)
       -t             - Test config. Error message to stderr + non-zero exit code on err
       -a <address>   - Bind to IP address
       -A <address>   - Bind to IPv6 address
       -b <port>      - Bind to port
       -B <port>      - Bind to port (IPv6)
       -h             - Print this help
root@router:~# cat /etc/init.d/umurmur
#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2008 OpenWrt.org

START=90

PIDFILE="/var/run/umurmurd.pid"

start() {
        stop
        /usr/bin/umurmurd -r -p $PIDFILE
}

stop() {
        [ -f "$PIDFILE" ] && kill $(cat "$PIDFILE") 2>/dev/null >/dev/null
}
root@router:~#  cat /proc/version
Linux version 3.18.17 (xxx@desktop) (gcc version 4.8.3 (OpenWrt/Linaro GCC 4.8-2014.04 r46001) ) #1 Thu Jul 2 13:16:40 KRAT 2015
```

**Comment by omor1** [comment]
It looks like umurmur was compiled without realtime priority, but the init script tries activating it anyways.

**Comment by unikum** [comment]
I built all packages with openwrt build root scripts. Seems we need to edit the Makefile.

**Comment by fmorgner** [comment]
As far as I can tell, the uMurmur build environments (Autotools and CMake) should check the availability of realtime priority and enable it if possible. Sadly i don't own a device running OpenWRT so i can't check if thats what its doing. Maybe @fatbob313 can verify this.

**Comment by fatbob313** [comment]
I think this is since OpenWRT changed default clib to musl that doesn't
have support for the Posix realtime stuff.
Den 12 jul 2015 13:19 skrev "Felix Morgner" <notifications@github.com>:

**Comment by fmorgner** [comment]
Thanks for the info @fatbob313!

After doing some research into [musl](http://www.musl-libc.org/) I think it might be possible that the way they are distributing their library might throw Autotools and CMake off track. It looks like they are shipping [one large monolithic binary](http://www.musl-libc.org/faq.html) and it might be possible that the configuration tools are unable to find clock_gettime in librt since they ship an empty file just to satisfy the linker.

I do not know how the different build systems look for symbols in libraries but my guess is they are "grepping" for the symbol in some way. Since the library file is empty the build system is unable to find the symbol and thus concludes that there is no support for realtime functionality on the system.

It might be worth investigation this issue further but I do not have access to an OpenWRT running device.

**Comment by fatbob313** [comment]
I don't think the autoconf/CMake scripts check for this. It's all done here;
https://github.com/umurmur/umurmur/blob/master/src/main.c#L44. The simple solution is of course to remove the '-r' switch in the startup script for OpenWRT. Possibly the current C-library could be detected from the startup script and the switch added conditionally. Anyone know if this is possible?

**Comment by fmorgner** [comment]
Is this still an issue?

**Comment by fatbob313** [comment]
Fixed by removing -r switch in init script in 7363653d0b389d7c4b2e429418afc290efa35af7
